using LinguaSpace.Application.Common.Interfaces;
using LinguaSpace.Application.Common.Security;

namespace LinguaSpace.Application.Auth.Commands.VerifyEmail;

/// <summary>
/// Confirms a user's email address using the token sent at registration.
/// The token is generated by ASP.NET Identity's UserManager.GenerateEmailConfirmationTokenAsync.
///
/// Security note: We require authentication so that the userId comes from the JWT claim,
/// not from an untrusted request body — preventing token reuse across users.
/// </summary>
[Authorize]
public record VerifyEmailCommand(string Token) : IRequest;

public class VerifyEmailCommandHandler : IRequestHandler<VerifyEmailCommand>
{
    private readonly IIdentityService _identityService;
    private readonly IUser _currentUser;

    public VerifyEmailCommandHandler(IIdentityService identityService, IUser currentUser)
    {
        _identityService = identityService;
        _currentUser = currentUser;
    }

    public async Task Handle(VerifyEmailCommand request, CancellationToken cancellationToken)
    {
        string userId = _currentUser.Id ?? throw new UnauthorizedAccessException();

        Result result = await _identityService.VerifyEmailAsync(userId, request.Token);

        result.ThrowOnFailure();
    }
}
