<Project Sdk="Aspire.AppHost.Sdk/13.2.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>LinguaSpace.AppHost</RootNamespace>
    <AssemblyName>LinguaSpace.AppHost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.Azure.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Azure.ResourceManager" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\Web\Web.csproj" />
  </ItemGroup>

</Project>
