global using Ardalis.GuardClauses;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using MediatR;
global using LinguaSpace.Application.Common.Models;
global using LinguaSpace.Domain.Entities;
global using LinguaSpace.Domain.Enums;
global using ValidationException = LinguaSpace.Application.Common.Exceptions.ValidationException;
global using NotFoundException = LinguaSpace.Application.Common.Exceptions.NotFoundException;
global using ForbiddenAccessException = LinguaSpace.Application.Common.Exceptions.ForbiddenAccessException;
